services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=inventory_db'
      - 'MYSQL_PASSWORD=inventory_password'
      - 'MYSQL_ROOT_PASSWORD=root_password'
      - 'MYSQL_USER=inventory_user'
    ports:
      - '3307:3306'
