spring:
  datasource:
    url: jdbc:mysql://localhost:3307/inventory_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: inventory_user
    password: inventory_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:miaotingshuo@gmail.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true
    default-encoding: UTF-8
    test-connection: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: 86400000 # 24 hours in milliseconds

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Application-specific settings
app:
  alerts:
    notification-email: ${ALERTS_EMAIL:miaotingshuo@gmail.com}
    send-email-notifications: ${SEND_EMAIL_NOTIFICATIONS:true}
  contact:
    notification-email: ${CONTACT_EMAIL:miaotingshuo@gmail.com}
  email:
    from-name: "Smart Inventory Pro"
    support-email: ${SUPPORT_EMAIL:miaotingshuo@gmail.com}

logging:
  level:
    org.springframework.security: DEBUG
    com.inventory: DEBUG
    org.springframework.mail: INFO
    org.springframework.scheduling: INFO 